#!/usr/bin/env python3
"""Generate slacker's bash/zsh/fish completions from contrib/completions.json.

Single source of truth: completions.json holds command -> argtype. Each shell's
Tab-time runtime helpers are hand-written per-shell preambles here; the dispatch
table is generated from the JSON. Run with no args to regenerate all three
files in contrib/; run with --check to fail if a committed file is out of date.
"""
import argparse
import difflib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SPEC = os.path.join(HERE, "completions.json")

GEN_HEADER = ("# GENERATED by contrib/gen-completions.py from "
              "contrib/completions.json - do not edit by hand.\n")


def load_spec():
    with open(SPEC) as fh:
        return json.load(fh)


# --- command groupings, derived from the JSON ------------------------------

def selectors(spec):
    """Commands that offer @repo/@_tag selectors."""
    return [c for c, v in spec["commands"].items() if v.get("selector")]


def positional(spec, kind):
    """Commands whose bare-word completion is `kind`."""
    return [c for c, v in spec["commands"].items() if v.get("positional") == kind]


# --- bash ------------------------------------------------------------------

BASH_PREAMBLE = r'''# bash-completion for slacker (https://forge.slackware.nl/rizitis/slacker)

_slacker_config_dir() {
    local i
    for ((i = 1; i < ${#COMP_WORDS[@]}; i++)); do
        if [[ ${COMP_WORDS[i]} == --config-dir && -n ${COMP_WORDS[i+1]} ]]; then
            printf '%s' "${COMP_WORDS[i+1]}"
            return
        fi
    done
    printf '/etc/slacker'
}

_slacker_installed_names() {
    local db=/var/adm/packages
    [[ -d $db ]] || return
    command ls "$db" 2>/dev/null \
        | grep -Ev -- '-upgraded-[0-9]' \
        | sed -E 's/(-[^-]+){3}$//'
}

_slacker_repo_names() {
    local repos="$1/repos"
    [[ -f $repos ]] || return
    awk '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        {
            url = $3
            if (url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//)
                print $2
        }' "$repos"
}

_slacker_build_tags() {
    local repos="$1/repos" db=/var/adm/packages
    {
        if [[ -f $repos ]]; then
            awk '
                /^[[:space:]]*#/ { next }
                /^[[:space:]]*$/ { next }
                {
                    url = $3
                    if (!(url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) && NF >= 3)
                        print $3
                }' "$repos"
        fi
        if [[ -d $db ]]; then
            command ls "$db" 2>/dev/null \
                | grep -Ev -- '-upgraded-[0-9]' \
                | sed -E 's/.*-([^-]+)$/\1/; s/^[0-9]+//' \
                | grep -v '^$'
        fi
    } | sort -u
}

_slacker_template_names() {
    local dir="$1/templates"
    [[ -d $dir ]] || return
    command ls "$dir" 2>/dev/null | sed -E 's/\.template$//'
}
'''


def emit_bash(spec):
    cmds = " ".join(spec["commands"].keys())
    gflags = " ".join(spec["_global_flags"])
    sel = "|".join(selectors(spec))
    installed = "|".join(positional(spec, "installed"))
    repo = "|".join(positional(spec, "repo"))
    tmpl = "|".join(positional(spec, "template"))

    flag_cases = ""
    for c, v in spec["commands"].items():
        if v.get("flags"):
            flag_cases += "            %s) flags+=' %s' ;;\n" % (c, " ".join(v["flags"]))

    out = []
    out.append(GEN_HEADER)
    out.append(BASH_PREAMBLE)
    out.append("\n_slacker_commands='%s'\n" % cmds)
    out.append("_slacker_global_flags='%s'\n" % gflags)
    out.append(r'''
_slacker_dispatch() {
    local config; config=$(_slacker_config_dir)

    if [[ $prev == --config-dir ]]; then
        compopt -o dirnames 2>/dev/null
        COMPREPLY=()
        return
    fi

    if [[ $cur == -* ]]; then
        local flags="$_slacker_global_flags"
        case $sub in
''' + flag_cases + r'''        esac
        COMPREPLY=($(compgen -W "$flags" -- "$cur"))
        return
    fi

    if [[ $sub == download && ( $prev == -o || $prev == --output ) ]]; then
        compopt -o dirnames 2>/dev/null
        COMPREPLY=()
        return
    fi

    case $sub in
        ''' + sel + r''')
            if [[ $cur == @* ]]; then
                local names tags list body
                names=$(_slacker_repo_names "$config")
                tags=$(_slacker_build_tags "$config")
                list=""
                for body in $names; do list+=" @$body"; done
                for body in $tags;  do list+=" @$body"; done
                COMPREPLY=($(compgen -W "$list" -- "$cur"))
                return
            fi
            ;;
    esac

    case $sub in
        ''' + installed + r''')
            COMPREPLY=($(compgen -W "$(_slacker_installed_names)" -- "$cur")) ;;
        ''' + repo + r''')
            COMPREPLY=($(compgen -W "$(_slacker_repo_names "$config")" -- "$cur")) ;;
        ''' + tmpl + r''')
            COMPREPLY=($(compgen -W "$(_slacker_template_names "$config")" -- "$cur")) ;;
        pin)
            if [[ $cur != *:* ]]; then
                local r list=""
                for r in $(_slacker_repo_names "$config"); do list+=" $r:"; done
                compopt -o nospace 2>/dev/null
                COMPREPLY=($(compgen -W "$list" -- "$cur"))
            fi ;;
    esac
}

_slacker() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur=${COMP_WORDS[COMP_CWORD]}
        prev=${COMP_WORDS[COMP_CWORD-1]}
    }

    local sub="" i
    for ((i = 1; i < COMP_CWORD; i++)); do
        case ${COMP_WORDS[i]} in
            --config-dir) ((i++)) ;;
            -*) ;;
            *) sub=${COMP_WORDS[i]}; break ;;
        esac
    done

    if [[ -z $sub ]]; then
        if [[ $cur == -* ]]; then
            COMPREPLY=($(compgen -W "$_slacker_global_flags" -- "$cur"))
        else
            COMPREPLY=($(compgen -W "$_slacker_commands" -- "$cur"))
        fi
        return
    fi

    _slacker_dispatch
}

complete -F _slacker slacker
''')
    return "".join(out)


# --- zsh --------------------------------------------------------------------

ZSH_PREAMBLE = r'''_slacker_config_dir() {
    local i
    for (( i = 2; i <= $#words; i++ )); do
        if [[ ${words[i]} == --config-dir && -n ${words[i+1]} ]]; then
            print -r -- ${words[i+1]}
            return
        fi
    done
    print -r -- /etc/slacker
}

_slacker_installed_names() {
    local db=/var/adm/packages
    [[ -d $db ]] || return
    command ls $db 2>/dev/null \
        | grep -Ev -- '-upgraded-[0-9]' \
        | sed -E 's/(-[^-]+){3}$//'
}

_slacker_repo_names() {
    local repos=$1/repos
    [[ -f $repos ]] || return
    awk '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        { url = $3
          if (url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) print $2 }' $repos
}

_slacker_build_tags() {
    local repos=$1/repos db=/var/adm/packages
    {
        [[ -f $repos ]] && awk '
            /^[[:space:]]*#/ { next }
            /^[[:space:]]*$/ { next }
            { url = $3
              if (!(url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) && NF >= 3) print $3 }' $repos
        [[ -d $db ]] && command ls $db 2>/dev/null \
            | grep -Ev -- '-upgraded-[0-9]' \
            | sed -E 's/.*-([^-]+)$/\1/; s/^[0-9]+//' | grep -v '^$'
    } | sort -u
}

_slacker_template_names() {
    local dir=$1/templates
    [[ -d $dir ]] || return
    command ls $dir 2>/dev/null | sed -E 's/\.template$//'
}
'''


def emit_zsh(spec):
    cmd_lines = " ".join("'%s'" % c for c in spec["commands"])
    gflags = " ".join("'%s'" % f for f in spec["_global_flags"])
    sel = set(selectors(spec))
    installed = set(positional(spec, "installed"))
    repo = set(positional(spec, "repo"))
    tmpl = set(positional(spec, "template"))

    def case_for(names, body):
        if not names:
            return ""
        pat = "|".join(sorted(names))
        return "        (%s)\n%s\n            ;;\n" % (pat, body)

    # A command may complete @-selectors AND a bare positional (e.g. remove,
    # install-new). Build one arm per command union so the case patterns stay
    # disjoint.
    arms = ""
    for c in spec["commands"]:
        is_sel = c in sel
        pos = spec["commands"][c]["positional"]
        if not is_sel and pos == "none":
            continue
        body_lines = []
        if is_sel:
            body_lines.append(
                "            if [[ $PREFIX == @* ]]; then\n"
                "                local -a sels\n"
                "                sels=( ${(f)\"$(_slacker_repo_names $cfg)\"} ${(f)\"$(_slacker_build_tags $cfg)\"} )\n"
                "                sels=( ${sels/#/@} )\n"
                "                compadd -a sels\n"
                "                return\n"
                "            fi")
        if pos == "installed":
            body_lines.append("            compadd ${(f)\"$(_slacker_installed_names)\"}")
        elif pos == "repo":
            body_lines.append("            compadd ${(f)\"$(_slacker_repo_names $cfg)\"}")
        elif pos == "template":
            body_lines.append("            compadd ${(f)\"$(_slacker_template_names $cfg)\"}")
        elif pos == "repo:pkg":
            body_lines.append(
                "            if [[ $PREFIX != *:* ]]; then\n"
                "                local -a repos\n"
                "                repos=( ${(f)\"$(_slacker_repo_names $cfg)\"} )\n"
                "                compadd -S ':' -- $repos\n"
                "            fi")
        arms += case_for({c}, "\n".join(body_lines))

    # Per-subcommand extra flags, as a zsh case that appends to $flags.
    flag_arms = ""
    for c, v in spec["commands"].items():
        if v.get("flags"):
            extra = " ".join("'%s'" % f for f in v["flags"])
            flag_arms += "        (%s) flags+=( %s ) ;;\n" % (c, extra)

    body = ZSH_PREAMBLE + r'''

_slacker() {
    local cfg; cfg=$(_slacker_config_dir)
    local -a cmds; cmds=( ''' + cmd_lines + r''' )
    local -a gflags; gflags=( ''' + gflags + r''' )

    if (( CURRENT == 2 )); then
        compadd -a cmds
        compadd -a gflags
        return
    fi

    local sub; sub=${words[2]}

    # The value after --config-dir is a directory.
    if [[ ${words[CURRENT-1]} == --config-dir ]]; then
        _files -/
        return
    fi

    # A flag is being typed: global flags plus any this subcommand adds.
    if [[ $PREFIX == -* ]]; then
        local -a flags; flags=( $gflags )
        case $sub in
''' + flag_arms + r'''        esac
        compadd -a flags
        return
    fi

    case $sub in
''' + arms + r'''    esac
}

_slacker "$@"
'''
    # zsh autoload requires #compdef on the very first line.
    return "#compdef slacker\n" + GEN_HEADER + body


# --- fish -------------------------------------------------------------------

FISH_PREAMBLE = r'''# fish completion for slacker

function __slacker_config_dir
    set -l toks (commandline -opc 2>/dev/null)
    for i in (seq (count $toks))
        if test "$toks[$i]" = --config-dir
            set -l n (math $i + 1)
            if test $n -le (count $toks)
                echo $toks[$n]
                return
            end
        end
    end
    echo /etc/slacker
end

function __slacker_installed_names
    test -d /var/adm/packages; or return
    command ls /var/adm/packages 2>/dev/null \
        | grep -Ev -- '-upgraded-[0-9]' \
        | sed -E 's/(-[^-]+){3}$//'
end

function __slacker_repo_names
    set -l repos (__slacker_config_dir)/repos
    test -f $repos; or return
    awk '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        { url = $3
          if (url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) print $2 }' $repos
end

function __slacker_build_tags
    set -l repos (__slacker_config_dir)/repos
    begin
        test -f $repos; and awk '
            /^[[:space:]]*#/ { next }
            /^[[:space:]]*$/ { next }
            { url = $3
              if (!(url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) && NF >= 3) print $3 }' $repos
        test -d /var/adm/packages; and command ls /var/adm/packages 2>/dev/null \
            | grep -Ev -- '-upgraded-[0-9]' \
            | sed -E 's/.*-([^-]+)$/\1/; s/^[0-9]+//' | grep -v '^$'
    end | sort -u
end

function __slacker_selectors
    printf '@%s\n' (__slacker_repo_names) (__slacker_build_tags)
end

function __slacker_template_names
    set -l dir (__slacker_config_dir)/templates
    test -d $dir; or return
    command ls $dir 2>/dev/null | sed -E 's/\.template$//'
end

# true when no subcommand word has been typed yet
function __slacker_no_sub
    set -l toks (commandline -opc 2>/dev/null)
    set -e toks[1]
    for t in $toks
        switch $t
            case --config-dir '-*'
                continue
            case '*'
                return 1
        end
    end
    return 0
end

# true when the typed subcommand is one of $argv
function __slacker_using
    set -l toks (commandline -opc 2>/dev/null)
    set -e toks[1]
    for t in $toks
        switch $t
            case --config-dir '-*'
                continue
            case '*'
                contains -- $t $argv; and return 0
                return 1
        end
    end
    return 1
end
'''


def emit_fish(spec):
    lines = [GEN_HEADER, FISH_PREAMBLE, ""]
    # subcommands, only offered before a subcommand word is typed
    # Disable fish's default filename completion for slacker; every context
    # that wants candidates adds them explicitly below. Without this, commands
    # that take no argument (update, search, help, ...) fall back to completing
    # files in the current directory.
    lines.append("complete -c slacker -f")
    lines.append("")
    for c in spec["commands"]:
        lines.append("complete -c slacker -n __slacker_no_sub -f -a '%s'" % c)
    lines.append("")
    # global flags, always available
    for f in spec["_global_flags"]:
        if f == "--config-dir":
            # takes a directory argument
            lines.append("complete -c slacker -l config-dir "
                         "-r -f -a '(__fish_complete_directories)'")
        elif f.startswith("--"):
            lines.append("complete -c slacker -l '%s'" % f[2:])
        else:
            lines.append("complete -c slacker -s '%s'" % f[1:])
    lines.append("")

    def using(names):
        return "__slacker_using " + " ".join(sorted(names))

    inst = positional(spec, "installed")
    repo = positional(spec, "repo")
    tmpl = positional(spec, "template")
    sel = selectors(spec)

    if sel:
        lines.append("complete -c slacker -n '%s' -f -a '(__slacker_selectors)'" % using(sel))
    if inst:
        lines.append("complete -c slacker -n '%s' -f -a '(__slacker_installed_names)'" % using(inst))
    if repo:
        lines.append("complete -c slacker -n '%s' -f -a '(__slacker_repo_names)'" % using(repo))
    if tmpl:
        lines.append("complete -c slacker -n '%s' -f -a '(__slacker_template_names)'" % using(tmpl))
    # pin: repo: prefixes
    for c in positional(spec, "repo:pkg"):
        lines.append("complete -c slacker -n '__slacker_using %s' -f "
                     "-a '(printf \"%%s:\\n\" (__slacker_repo_names))'" % c)
    # per-subcommand extra flags
    for c, v in spec["commands"].items():
        for f in v.get("flags", []):
            if f.startswith("--"):
                lines.append("complete -c slacker -n '__slacker_using %s' -l '%s'" % (c, f[2:]))
            else:
                lines.append("complete -c slacker -n '__slacker_using %s' -s '%s'" % (c, f[1:]))
    return "\n".join(lines) + "\n"


EMITTERS = {
    "slacker-completion.bash": emit_bash,
    "slacker-completion.zsh": emit_zsh,
    "slacker.fish": emit_fish,
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit nonzero if any committed file is out of date")
    args = ap.parse_args()
    spec = load_spec()

    rc = 0
    for fname, emit in EMITTERS.items():
        path = os.path.join(HERE, fname)
        new = emit(spec)
        if args.check:
            old = open(path).read() if os.path.exists(path) else ""
            if old != new:
                rc = 1
                sys.stderr.write("DRIFT: %s is out of date; run gen-completions.py\n" % fname)
                for line in difflib.unified_diff(
                        old.splitlines(True), new.splitlines(True),
                        fromfile=fname + " (committed)", tofile=fname + " (regenerated)"):
                    sys.stderr.write(line)
        else:
            with open(path, "w") as fh:
                fh.write(new)
    return rc


if __name__ == "__main__":
    sys.exit(main())
