# GENERATED by contrib/gen-completions.py from contrib/completions.json - do not edit by hand.

# fish completion for slacker

function __slacker_config_dir
    set -l toks (commandline -opc 2>/dev/null)
    for i in (seq (count $toks))
        if test "$toks[$i]" = --config-dir
            set -l n (math $i + 1)
            if test $n -le (count $toks)
                echo $toks[$n]
                return
            end
        end
    end
    echo /etc/slacker
end

function __slacker_installed_names
    test -d /var/adm/packages; or return
    command ls /var/adm/packages 2>/dev/null \
        | grep -Ev -- '-upgraded-[0-9]' \
        | sed -E 's/(-[^-]+){3}$//'
end

function __slacker_repo_names
    set -l repos (__slacker_config_dir)/repos
    test -f $repos; or return
    awk '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        { url = $3
          if (url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) print $2 }' $repos
end

function __slacker_build_tags
    set -l repos (__slacker_config_dir)/repos
    begin
        test -f $repos; and awk '
            /^[[:space:]]*#/ { next }
            /^[[:space:]]*$/ { next }
            { url = $3
              if (!(url ~ /:\/\// || url == "mirror" || url ~ /^mirror\//) && NF >= 3) print $3 }' $repos
        test -d /var/adm/packages; and command ls /var/adm/packages 2>/dev/null \
            | grep -Ev -- '-upgraded-[0-9]' \
            | sed -E 's/.*-([^-]+)$/\1/; s/^[0-9]+//' | grep -v '^$'
    end | sort -u
end

function __slacker_selectors
    printf '@%s\n' (__slacker_repo_names) (__slacker_build_tags)
end

function __slacker_template_names
    set -l dir (__slacker_config_dir)/templates
    test -d $dir; or return
    command ls $dir 2>/dev/null | sed -E 's/\.template$//'
end

# true when no subcommand word has been typed yet
function __slacker_no_sub
    set -l toks (commandline -opc 2>/dev/null)
    set -e toks[1]
    for t in $toks
        switch $t
            case --config-dir '-*'
                continue
            case '*'
                return 1
        end
    end
    return 0
end

# true when the typed subcommand is one of $argv
function __slacker_using
    set -l toks (commandline -opc 2>/dev/null)
    set -e toks[1]
    for t in $toks
        switch $t
            case --config-dir '-*'
                continue
            case '*'
                contains -- $t $argv; and return 0
                return 1
        end
    end
    return 1
end


complete -c slacker -n __slacker_no_sub -f -a 'update'
complete -c slacker -n __slacker_no_sub -f -a 'search'
complete -c slacker -n __slacker_no_sub -f -a 'file-search'
complete -c slacker -n __slacker_no_sub -f -a 'info'
complete -c slacker -n __slacker_no_sub -f -a 'list-repos'
complete -c slacker -n __slacker_no_sub -f -a 'status'
complete -c slacker -n __slacker_no_sub -f -a 'install'
complete -c slacker -n __slacker_no_sub -f -a 'upgrade'
complete -c slacker -n __slacker_no_sub -f -a 'reinstall'
complete -c slacker -n __slacker_no_sub -f -a 'remove'
complete -c slacker -n __slacker_no_sub -f -a 'revert-pkg'
complete -c slacker -n __slacker_no_sub -f -a 'download'
complete -c slacker -n __slacker_no_sub -f -a 'upgrade-all'
complete -c slacker -n __slacker_no_sub -f -a 'upgrade-dist'
complete -c slacker -n __slacker_no_sub -f -a 'install-new'
complete -c slacker -n __slacker_no_sub -f -a 'clean-system'
complete -c slacker -n __slacker_no_sub -f -a 'clean-cache'
complete -c slacker -n __slacker_no_sub -f -a 'new-config'
complete -c slacker -n __slacker_no_sub -f -a 'check-updates'
complete -c slacker -n __slacker_no_sub -f -a 'show-changelog'
complete -c slacker -n __slacker_no_sub -f -a 'history'
complete -c slacker -n __slacker_no_sub -f -a 'find-mirror'
complete -c slacker -n __slacker_no_sub -f -a 'generate-template'
complete -c slacker -n __slacker_no_sub -f -a 'install-template'
complete -c slacker -n __slacker_no_sub -f -a 'remove-template'
complete -c slacker -n __slacker_no_sub -f -a 'delete-template'
complete -c slacker -n __slacker_no_sub -f -a 'frozen'
complete -c slacker -n __slacker_no_sub -f -a 'unfrozen'
complete -c slacker -n __slacker_no_sub -f -a 'pin'
complete -c slacker -n __slacker_no_sub -f -a 'unpin'
complete -c slacker -n __slacker_no_sub -f -a 'add-repo'
complete -c slacker -n __slacker_no_sub -f -a 'del-repo'
complete -c slacker -n __slacker_no_sub -f -a 'pri-repo'
complete -c slacker -n __slacker_no_sub -f -a 'add-tag'
complete -c slacker -n __slacker_no_sub -f -a 'del-tag'
complete -c slacker -n __slacker_no_sub -f -a 'vet-repo'
complete -c slacker -n __slacker_no_sub -f -a 'trust-repo'
complete -c slacker -n __slacker_no_sub -f -a 'distrust-repo'
complete -c slacker -n __slacker_no_sub -f -a 'help'

complete -c slacker -l config-dir -r -f -a '(__fish_complete_directories)'
complete -c slacker -l 'yes'
complete -c slacker -s 'y'
complete -c slacker -l 'dry-run'
complete -c slacker -l 'no-deps'
complete -c slacker -l 'help'
complete -c slacker -s 'h'
complete -c slacker -l 'version'
complete -c slacker -s 'V'

complete -c slacker -n '__slacker_using download install reinstall remove upgrade' -f -a '(__slacker_selectors)'
complete -c slacker -n '__slacker_using history info reinstall remove revert-pkg unpin' -f -a '(__slacker_installed_names)'
complete -c slacker -n '__slacker_using clean-cache del-repo distrust-repo install-new pri-repo show-changelog trust-repo vet-repo' -f -a '(__slacker_repo_names)'
complete -c slacker -n '__slacker_using delete-template install-template remove-template' -f -a '(__slacker_template_names)'
complete -c slacker -n '__slacker_using pin' -f -a '(printf "%s:\n" (__slacker_repo_names))'
complete -c slacker -n '__slacker_using download' -s 'o'
complete -c slacker -n '__slacker_using download' -l 'output'
complete -c slacker -n '__slacker_using history' -l 'last'
complete -c slacker -n '__slacker_using history' -l 'since'
complete -c slacker -n '__slacker_using history' -l 'installed'
complete -c slacker -n '__slacker_using history' -l 'removed'
complete -c slacker -n '__slacker_using history' -l 'upgraded'
